"""init tables

Revision ID: 3eaa52c062bd
Revises: 293c85e9d496
Create Date: 2026-03-24 21:05:37.955520

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '3eaa52c062bd'
down_revision: Union[str, Sequence[str], None] = '293c85e9d496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
