"""add refresh_tokens table

Revision ID: a72c1ce0486d
Revises: ba8e611af231
Create Date: 2026-04-02 14:36:58.893000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72c1ce0486d'
down_revision: Union[str, Sequence[str], None] = 'ba8e611af231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('books', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('books', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('books', 'author',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
